### ISSUE TITLE
compile for elk-os

### ISSUE THREAD

**Issue by yudashuixiao1** [GuitarML/TS-M1N3#12]
Great work! It can build in elk-os like NeuralPi?

**Comment by GuitarML** [comment]
@yudashuixiao1 The code probably wouldn't build in elk-os as written, but with minor modifications it could. Basically anything that references the GUI/plugin editor would need to be taken out and handled elsewhere. It would also need to be updated with OSC protocol or you wouldn't be able to use the controls.
